// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJllTC4-ydn2xjhJBLHQ9tgXhde-e8xs',
    appId: '1:380861290492:web:e1d33565d72b9419994479',
    messagingSenderId: '380861290492',
    projectId: 'fyp2-92b3f',
    authDomain: 'fyp2-92b3f.firebaseapp.com',
    storageBucket: 'fyp2-92b3f.firebasestorage.app',
    measurementId: 'G-R0B31065D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVJOeSjZaraF_K5AHtcv9qFhqIZOiyCs',
    appId: '1:380861290492:android:e20b0bd6c00e371f994479',
    messagingSenderId: '380861290492',
    projectId: 'fyp2-92b3f',
    storageBucket: 'fyp2-92b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hNzPx2rjaavtgTustLC4_BS4WbAre2I',
    appId: '1:380861290492:ios:140a8d00cea0a5a2994479',
    messagingSenderId: '380861290492',
    projectId: 'fyp2-92b3f',
    storageBucket: 'fyp2-92b3f.firebasestorage.app',
    iosBundleId: 'com.example.app12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hNzPx2rjaavtgTustLC4_BS4WbAre2I',
    appId: '1:380861290492:ios:140a8d00cea0a5a2994479',
    messagingSenderId: '380861290492',
    projectId: 'fyp2-92b3f',
    storageBucket: 'fyp2-92b3f.firebasestorage.app',
    iosBundleId: 'com.example.app12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSJllTC4-ydn2xjhJBLHQ9tgXhde-e8xs',
    appId: '1:380861290492:web:5f064a30fe484400994479',
    messagingSenderId: '380861290492',
    projectId: 'fyp2-92b3f',
    authDomain: 'fyp2-92b3f.firebaseapp.com',
    storageBucket: 'fyp2-92b3f.firebasestorage.app',
    measurementId: 'G-880W64RB53',
  );
}
